-- DROP TABLE IF EXISTS PRODUCT_ITEM;

INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(10,'lowcarbproteinshake.png','Protein',100);

INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(11,'lowcarbproteinshake.png','Protein1',100);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(12,'lowcarbproteinshake.png','Protein2',100);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(13,'lowcarbproteinshake.png','Protein3',100);

INSERT INTO USER_DETAILS(ADDRESS,MODEOFPAYMENT,FULLNAME,PASSWORD,USERNAME,USERTYPE) VALUES('dublin','COD','Amit Kumar','1234','amit','customer');
INSERT INTO USER_DETAILS(ADDRESS,MODEOFPAYMENT,FULLNAME,PASSWORD,USERNAME,USERTYPE) VALUES('dublin','COD','Admin Kumar','admin','admin','admin');
-- CREATE TABLE PRODUCT_ITEM