-- DROP TABLE IF EXISTS PRODUCT_ITEM;

INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(10,'lowcarbproteinshake.png','Protein',100);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(11,'Bcomplex.png','B Complex',10);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(30,'Digestive.jpg','Digestive Enzymes',55);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(13,'vitaminC.png','Vitamin C',10);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(20,'DentalKit.jpeg','Dental Kit',38);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(120,'calciumcarbonate.jpg','CC',20);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(145,'multivitamin.jpg','Multi Vitamin',15);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(130,'Omega3.jpg','Omega3',12);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(100,'vitaminA.jpg','Vitamin A',20);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(40,'Dettolfloorwipes.jpg','Floor Wipes - Dettol',5);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(50,'handsanitizinggel.jpg','Hand Sanitizing Gel',10);
INSERT INTO PRODUCT_ITEM(AVAILABLE_STOCK,IMAGEURL,PRODUCT_NAME,PRICE) VALUES(13,'HandTissue.JPG','Hand Tissue',2);

INSERT INTO USER_DETAILS(ADDRESS,MODEOFPAYMENT,FULLNAME,PASSWORD,USERNAME,USERTYPE) VALUES('dublin','COD','Amit Kumar','1234','amit','customer');
INSERT INTO USER_DETAILS(ADDRESS,MODEOFPAYMENT,FULLNAME,PASSWORD,USERNAME,USERTYPE) VALUES('dublin','COD','Admin Kumar','admin','admin','admin');
-- CREATE TABLE PRODUCT_ITEM